### PR TITLE
typescript types

### PR DESCRIPTION
**Pull request by jer-sen**

### CODE REVIEW

**Review by semmel — APPROVED** [review]
👍

**Comment by jer-sen** [comment]
@semmel can you release a new version ?

**Comment by semmel** [comment]
Yes of course first thing when I am in office.

**Comment by semmel** [comment]
Done!

**Comment by jer-sen** [comment]
thanks, keep in mind that you will have to update these typescript definitions if your API signature changes

**Comment by semmel** [comment]
👌

**Pull request merged**
